### ISSUE TITLE
Some hotkeys still dont work

### ISSUE THREAD

**Issue by brianteeman** [ranbuch/accessibility#68]
Verified on your demo site

Module or Function | Hotkey | Help Text | Hotkey
--- | --- | --- | ---
Toggle Menu | CTRL + ALT + A | none | ❌
Gray Hues | CTRL + ALT + G | ✔️ | ✔️
Underline Links | CTRL + ALT + U | ✔️ | ✔️
Big Cursor | CTRL + ALT + C | ✔️ | ✔️
Reading Guide | CTRL + ALT + R | ✔️ | ✔️
Text To Speech | CTRL + ALT + T | none| ✔️ 
Speech To Text | CTRL + ALT + S | none | ✔️

**Comment by ranbuch** [comment]
@brianteeman actually `Ctrl` + `Alt` + `A` does toggle the menu for me.

I've added help text to all missing sections (version `5.0.5`).

**Comment by brianteeman** [comment]
Which browser are you using?

I still can't get ctr alt a to work for me AND it wasnt on the documented list but I see that invert colors has a hotkey as well (ctrl alt i) and that one dosesnt seem to work either

**Comment by brianteeman** [comment]
found it - they must have been conflicting with another hotkey - I changed them to y and n and it worked

Maybe you know of a tool to check what is being triggered by a hotkey

**Comment by ranbuch** [comment]
> Maybe you know of a tool to check what is being triggered by a hotkey

Not really but I've merged your PR, thank you for that. version 5.0.6 has been published accordingly.

**Comment by brianteeman** [comment]
Sorry if there is any confusion - when I said " I changed them to y and n and it worked" that was just for testing to make sure it was a key conflict. That was not in the pr - just some other missed stuff.

**Comment by ranbuch** [comment]
I'm using Chrome on Windows. Just tried `Ctrl` + `Alt` + `A` on Safari (Mac) and it works fine.

**Comment by brianteeman** [comment]
obviously a conflict with something I have installed on my pc then

**Comment by brianteeman** [comment]
retested on chrome without any extensions and still have the issues reported in the first post

**Comment by ranbuch** [comment]
You'll need to be more specific on how to reproduce this issue.

https://github.com/ranbuch/accessibility/assets/3777546/182fc685-6eb1-457c-b651-0e136a0a62a3

**Comment by brianteeman** [comment]
This recording was made with chrome 125 on windows 11. Running in incognito mode so no browser extensions are interfering. Keypresses are displayed using [keyviz](https://github.com/mulaRahul/keyviz/) - the same happens without that application running - it was just for display

https://youtu.be/Kolz65C54vU

**Comment by ranbuch** [comment]
@brianteeman according to the video I see that all of the hotkeys doesn't work. I was under the impression that most of them are working by looking at the table at the top comment.

**Comment by brianteeman** [comment]
I think the video is not clear. I will try again tomorrow
